name: entry-point-ci

on: 
  push:
    branches: 
<<<<<<< HEAD
=======
      - main
>>>>>>> 7bcd0ee (first workflow)
      - dev
      - "HSSH-**"
  pull_request:
    branches: 
      - main
      - dev
      - "HSSH-**"
  workflow_dispatch:

jobs:
  back-pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Clone project
      uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
<<<<<<< HEAD
      run: npm ci
    
    - name: JS quality
      run: npm run lint-fix

    - name: Build
      run: npm run build
    
    # - name: Test
    #   run: npm test
=======
      run: npm ci
>>>>>>> 7bcd0ee (first workflow)
